### PR TITLE
Fix `ByteBuffer` usage for JDK8 jre

### PR DESCRIPTION
**Pull request by Iapetus999**
## Description of changes in release / Impact of release:
Fix for running in JRE 8

## Documentation
(insert text here)

### Is this a breaking change?
- [ ] Yes
- [ ] No

### If you answered Yes then describe why is it so
(insert text here if applicable)

### Is there a way to disable the change?
- [ ] Use previous release
- [ ] Use a feature flag
- [ ] No

#### Additional details go here
(insert text here if applicable)

### CODE REVIEW

**Comment by mahmoudimus** [comment]
If tests pass, we merge and deploy.

**Review by mahmoudimus — APPROVED** [review]

**Comment by Iapetus999** [comment]
I don't know why the CircleCi tests aren't running

**Comment by Iapetus999** [comment]
retest this please

**Comment by moehajj** [comment]
it's because a larky-api script is failing to download some objects. I'm looking into it, most probably a credentials issue

**Pull request merged**
